#!/bin/bash

# MounRiverStudio is downloaded from https://www.mounriver.com/download
# Find the resource ID in Dev-Tools - Network panel after clicking the download link.
RESOURCE_ID=1940711724539809794

cd $(dirname $0)

if [ ! -d /tmp/MRS-linux-x64 ]
then
    URL=$(curl -s "https://api.mounriver.com/mountriver/api/version/getDownloadUrl?resourceId=$RESOURCE_ID" | jq -r .result)

    echo "Downloading mounriver from $URL"
    #curl -o /tmp/mounriver.tar.xz $URL

    echo "Extracting SVD files"
    #tar -C /tmp -xvf /tmp/mounriver.tar.xz MRS-linux-x64/resources/app/resources/linux/components/WCH/SDK/default/
fi

echo "Copying SVD files"
find /tmp/MRS-linux-x64/resources/app/resources/linux/components/WCH/SDK/default/ -name '*.svd' -exec cp {} . \;

for PROBLEM in CH57Xxx CH59Xxx
do
    rm -f ${PROBLEM}.svd
done

for svd_file in *.svd
do
    if [ -f "$svd_file" ]; then
        sed -i 's/<?xml version="1\.1"/<?xml version="1.0"/' "$svd_file"
    fi
done